server:
  port: 8080
swagger:
    enabled: true
    title: Spring Boot RestAssured Demo
    description: Spring Boot RestAssured Demo
    version: 1.0
    base-package: com.example.demo
    contact-name: Swagger
    contact-url:

spring:
    h2:
        console:
            enabled: true
            path: /h2-console
    application:
        name: my-job-portal-api
    datasource:
        url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;
        username: root
        password: root
        driver-class-name: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
    graphql:
      playground:
        endpoint: /graphql
        subscriptionEndpoint: /subscriptions
        enabled: true
        pageTitle: Playground
        cdn:
          enabled: false
          version: latest
        static-path:
          base: /api/vendor/playground/
          mapping: /playground/**
      schema-location-pattern: classpath:graphql/*.graphqls
      graphiql:
        enabled: true
        mapping: /graphiql/**


    #schema-json-file: schema.json
    #schema-json-file: classpath:graphql/schema.json
    #schema-json-file: file:graphq